### ISSUE TITLE
Please provide an example project

### ISSUE THREAD

**Issue by staticdev** [mattwcole/gelf-extensions-logging#1]
I followed the documentation, but I couldn't make it work. It would be nice if this lib had some example project to build/customize from it.

**Comment by mattwcole** [comment]
Sure, a sample app should be quite easy to create. If you just want to make sure your logging works with a local Graylog server, create a console app, install `Gelf.Extensions.Logging` and `Microsoft.Extensions.Logging` NuGet packages, and use the following code.

```csharp
using Gelf.Extensions.Logging;
using Microsoft.Extensions.Logging;

namespace ConsoleApp
{
    public class Program
    {
        public static void Main()
        {
            using (var loggerFactory = new LoggerFactory())
            {
                loggerFactory.AddGelf(new GelfLoggerOptions
                {
                    LogSource = "my-app",
                    Host = "localhost",
                    LogLevel = LogLevel.Information
                });

                var logger = loggerFactory.CreateLogger<Program>();
                logger.LogInformation("Hello");
            }
        }
    }
}
```

**Comment by mattwcole** [comment]
I have added a couple of sample projects that will hopefully help future users.
