### ISSUE TITLE
CorrelationId as AdditionalFields

### ISSUE THREAD

**Issue by shah-keyur** [mattwcole/gelf-extensions-logging#11]
Hi Mattwcole,

As Gelf providses the facility of Logger.BeginScope() to add additional field to structured log.

If I have to add the correlationId in every log then I have to do something like
using (_logger.BeginScope(("correlation_id", correlationId)))
{
    // Field will be added to all logs within this scope (using any ILogger<T> instance).
}

So for everylog I have to wrap with using statement.

Is there a way that  I dont have to write that everytime  but just done once.

A quick solution I think is like I care wrapper to loginfo/logerror/logdebug  with using  statement having correlation id as scop.

Do you suggest a better way?

Thanks,
Keyur

**Comment by mattwcole** [comment]
You don't have to create the scope with the same logger instance you pass the log to, so you can just create the scope once in your app. A good place to do this in ASP.NET could be in a [middleware](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-2.1&tabs=aspnetcore2x).

Here is an example middleware that will try to get the correlation ID from a HTTP header, and if it isn't found will generate a new random correlation ID.

```c#
public class CorrelationIdMiddleware
{
    private readonly RequestDelegate _next;
    private readonly IHttpContextAccessor _httpContextAccessor;
    private readonly ILogger<CorrelationIdMiddleware> _logger;

    public CorrelationIdMiddleware(RequestDelegate next,
        IHttpContextAccessor httpContextAccessor, ILogger<CorrelationIdMiddleware> logger)
    {
        _next = next;
        _httpContextAccessor = httpContextAccessor;
        _logger = logger;
    }

    public async Task Invoke(HttpContext context)
    {
        using (_logger.BeginScope(("correlation_id", GetCorrelationId())))
        {
            await _next.Invoke(context);
        }
    }

    private string GetCorrelationId()
    {
        return _httpContextAccessor.HttpContext.Request.Headers.TryGetValue("X-Correlation-ID", out var id)
            ? (string) id
            : $"my-application-name-{Guid.NewGuid()}";
    }
}
```

**Comment by shah-keyur** [comment]
Hi Mattwcole,

You are awesome! It works!

Just would like to know how the sope created in middleware passed to different logger instance?
Can you share something from where I can understand a bit more

Thanks,
Keyur

**Comment by shah-keyur** [comment]
Hi Mattwcole,

I found my answer as it traverses the sope from very current to the very first parent in a hierarchy.

So It just order of registering the middleware so that very first request should hit the CorrelationId middleware even before the authorization so the sope will begin from the very first request.

You can close this.

Again, many thanks.
-Keyur
