### ISSUE TITLE
Doesn't work with (the GELF input plugin for) Logstash 

### ISSUE THREAD

**Issue by beorn247** [mattwcole/gelf-extensions-logging#22]
It seems the Logstash Gelf input plugin only handles compressed Gelf which this library doesn't support (as far as I can tell). The readme, however, mentions that it can be used for sending logs to Logstash. Could the readme describe which input plugin to use with Logstash?

**Comment by beorn247** [comment]
Never mind, I found the UdpCompressionThreshold option by browsing the source now.

**Comment by mattwcole** [comment]
Thanks for pointing this out, I should add a section about this to the readme.
