### ISSUE TITLE
Support Func in AdditionalFields

### ISSUE THREAD

**Issue by tomap** [mattwcole/gelf-extensions-logging#26]
In AdditionalFields, it would be nice to support Func so that we can calculate fields from other values:

Example:
```
"HumanLevel", (m) => switch(m.Level){
case 1:
return "Error";
/***/
}
```

Here is the code to change in GelfMessageExtensions to allow that:

```
                if (field.Value is Func<GelfMessage, object> specialFunc)
                {
                    messageJson[$"_{field.Key}"] = specialFunc(message)?.ToString();
                }
                else if (IsNumeric(field.Value))
```

Tell me what you think :)

Note that the reason why I'm asking that is because my previous GELF appender was creating a "Level" field in plain text (Info, Debug, ...) that was very nice to filter on in graylog.
By switching to .Net Core & MS.Extension.Logging, we lost that capability, which forced us to fork your project and customize it.

The last "customized bit" of our fork is this little field.

I suspect there is a way to do that directly in GrayLog, but I could not find it and I'm not sure I'll be able/allowed to change that on our GrayLog instance

**Comment by mattwcole** [comment]
Hi, we just had a very similar request in #23, so perhaps this is something we should consider adding. Could you decorate `IGelfClient` so that the level is added to the additional fields? You would have to follow similar steps as in #23 to replace the default `IGelfClient`.

```csharp
public class SeverityGelfClientDecorator : IGelfClient
{
    private readonly IGelfClient _gelfClient;

    public SeverityGelfClientDecorator(IGelfClient gelfClient)
    {
        _gelfClient = gelfClient;
    }

    public Task SendMessageAsync(GelfMessage message)
    {
        message.AdditionalFields = message.AdditionalFields.Concat(new[]
        {
            new KeyValuePair<string, object>("severity", message.Level.ToString())
        });

        return _gelfClient.SendMessageAsync(message);
    }
}
```

There would be a bit of extra work as you would need a replacement `GelfLoggerProvider` too that would use the decorator instead of the default implementations. I'll take a closer look at supporting dynamic additional fields as well.

**Comment by Andreas-Hjortland** [comment]
I did some work which I considered using in a pull request if we decided to implement support for Func<> in the gelf logger itself.

I pushed the changes I did on my fork in the feature branch [#26-dynamic-field](https://github.com/Andreas-Hjortland/gelf-extensions-logging/tree/%2326-dynamic-field) just now as inspiration if you decide to implement this.

We are happy with the solution in #23 so we will probably not use this feature in the near future ourselves.

**Comment by tomap** [comment]
My need is to have an entry point to create new dynamic fields. 

I do not need any state, so using inheritance is unnecessary. Also, I'm not a fan of cloning an array for each log message.

I would prefer the Func<> solution. 

The code mentioned before seems good.
Otherwise you could introduce a serializer that would be in charge of this and let us overload it, to add capabilities to it, like support of Func<>

**Comment by Andreas-Hjortland** [comment]
I also extracted our way of Decorating the logger in [this gist](https://gist.github.com/Andreas-Hjortland/75e78e1c121bc1a35b1fab7cbdd6b773). You might find that useful if you want to solve the issue before we eventually get support for `Func<>` in AdditionalFields.

**Comment by mattwcole** [comment]
I don't plan to add support for `Func<GelfMessage, object>` in additional fields at the moment so will close this issue for now. Allowing message serialisation to be customised as suggested above could be a nice addition, although I suspect very few people would require that feature.
