### ISSUE TITLE
Logstash support

### ISSUE THREAD

**Issue by tomap** [mattwcole/gelf-extensions-logging#32]
I've seen issue #22 but it's still unclear to me is your extension is able to "feed" logstash "by default" or if it requires a plugin over logstash (like this one https://www.elastic.co/guide/en/logstash/current/plugins-inputs-gelf.html) 

I believe it's the second

Could you confirm?
Could anyone who used this scenario help ? @loxybjorn ?

Thank you!

**Comment by beorn247** [comment]
You need to use the Gelf plugin for Logstash and set UdpCompressionThreshold to 0.

**Comment by tomap** [comment]
ok, thank you!

**Comment by mattwcole** [comment]
Thanks @loxybjorn, I have added [a section](https://github.com/mattwcole/gelf-extensions-logging/blob/dev/README.md#compression) about compression and the Logstash plugin to the readme, so hopefully it will be more obvious for future users.
