### ISSUE TITLE
Include 'stringLevel' in log messages

### ISSUE THREAD

**Issue by mrmartan** [mattwcole/gelf-extensions-logging#34]
As the title says. There is only the numeric `level` which is not human friendly.

**Comment by mattwcole** [comment]
I believe this is an [issue with Graylog](https://github.com/graylog-labs/graylog2-web-interface/issues/1630), rather than this library. Some suggested solutions can be found [here](https://community.graylog.org/t/log-level-field-showing-its-code-how-to-show-log-level-as-warn-error-etc/8477).

**Comment by mrmartan** [comment]
I don't think so. Your library even isn't called `graylog-extensions-logging` and rightly so. Solving it with Graylog is workaround at best.

1) I am interested in GELF, not Graylog. We are not putting the messages into Graylog, rather leveraging GELF with ELK.
2) You can easily add it as an `additional field`
3) Serilog (and Serilog.Sinks.Graylog) does this.

I'd like this to work with Microsoft.Extensions.Logging and can't workaround it since i don't have access to log messages when configuring the log output (no surprise here).
