### ISSUE TITLE
Incompatibility with Netcore 3.0

### ISSUE THREAD

**Issue by m-jepson** [mattwcole/gelf-extensions-logging#37]
It seems this library does not go well with Microsoft.Extensions.Logging.Abstractions v. 3.0.
When I combine them, I get the following exception:

System.AggregateException: 'Could not load type 'Microsoft.Extensions.Logging.Internal.FormattedLogValues' from assembly 'Microsoft.Extensions.Logging.Abstractions, Version=3.0.0.0'

Even when I try to load v. 2.2.0 of the abstractions library into my netcore 3.0 app, it still produces this exception. Seems like the new framework is somehow forcing the 3.0 version.

**Comment by m-jepson** [comment]
Never mind, found the 1.5.2-pre2 version that already fixes this.

**Comment by mattwcole** [comment]
Thanks for reminding me to put the fix into a stable release! I'll publish a new version shortly.
