### ISSUE TITLE
HttpClient - HttpGelfClient 

### ISSUE THREAD

**Issue by thiagoloureiro** [mattwcole/gelf-extensions-logging#38]
Hi @mattwcole ,

On **HttpGelfClient** shouldn't we use a static httpClient? To avoid opening and closing connections, even if it's disposed takes a while to close the connection

See:

https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/

Thanks!

**Comment by mattwcole** [comment]
Hi, the `HttpClient` instance is a singleton. It has the same lifetime as [`HttpGelfClient`](https://github.com/mattwcole/gelf-extensions-logging/blob/dev/src/Gelf.Extensions.Logging/HttpGelfClient.cs#L10) which has the same lifetime as [`GelfLoggerProvider`](https://github.com/mattwcole/gelf-extensions-logging/blob/dev/src/Gelf.Extensions.Logging/GelfLoggerProvider.cs#L14) which is registered as a singleton [here](https://github.com/mattwcole/gelf-extensions-logging/blob/dev/src/Gelf.Extensions.Logging/LoggingBuilderExtensions.cs#L22).

**Comment by thiagoloureiro** [comment]
Ah cool! Sorry didn’t noticed that! We can close it .
Thanks for the good work in here mate, I’m starting to use this package in a big project ✌🏻

**Comment by mattwcole** [comment]
No problem, good luck with the project! 👍
