### ISSUE TITLE
request: .net core 3 builds - move from Newtonsoft.Json to System.Text.Json

### ISSUE THREAD

**Issue by RandomGHUser** [mattwcole/gelf-extensions-logging#39]
Microsoft is pushing the use of the new native System.Text.Json methods in 3.0 as a replacement to Newtonsoft.Json. 

As users migrate to the internal methods, relying on the Newtonsoft.JSON dependency will be redundant.  

Is there a plan to convert these methods to the native methods for the 3.0 builds in the future?

**Comment by mattwcole** [comment]
I think this would be worth doing yes. I can look into it when I get some time, but contributions are welcome if you need this urgently.
