### ISSUE TITLE
LogLevel not inherited from top level

### ISSUE THREAD

**Issue by mersadk** [mattwcole/gelf-extensions-logging#47]
If I configure GELF like this, I will receive messages from Microsoft packages to GrayLog.
GELF node doesn't contain LogLevel node.
```
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
    },
    "GELF": {
      ...
    }
  }
}
```

From what I understand GELF should inherit settings top level regarding LogLevel, but it doesn't. Is this intended behavior or bug?

**Comment by mattwcole** [comment]
Thanks for reporting, yes the log level should be inherited. I'll see if I can reproduce the issue.

**Comment by mattwcole** [comment]
I just tried this with one of the [sample apps](https://github.com/mattwcole/gelf-extensions-logging/tree/dev/samples/Gelf.Extensions.Logging.Samples.AspNetCore3) and it appears to be working. "Logging:LogLevel" is used when "Logging:GELF:LogLevel" is not set in the config. Maybe you are overriding your appsettings.json with appsettings.Development.json?

**Comment by mattwcole** [comment]
I'm going to close this for now, but feel free to re-open if you feel this is still an issue.
