### ISSUE TITLE
How to add client ip etc

### ISSUE THREAD

**Issue by meataxe** [mattwcole/gelf-extensions-logging#49]
Maybe a dumb question, but I'm not super familiar with logging in asp.net core and I can't see where to add fields like current user, client ip etc that would be available on the HttpContext but not available as part of this call `.ConfigureLogging((context, builder) => builder.AddGelf(...`?

**Comment by mattwcole** [comment]
Hi, sorry for the delay getting back to you. You can use a middleware like [this one](https://github.com/mattwcole/gelf-extensions-logging/issues/11#issuecomment-387725521) to add information about the current request as fields. Let me know if you have any other questions.
