### ISSUE TITLE
Message processing becomes a bottleneck when using the UDP client in an environment without DNS caching

### ISSUE THREAD

**Issue by svenvanheugten** [mattwcole/gelf-extensions-logging#50]
Every time [`GelfMessageProcessor`](https://github.com/mattwcole/gelf-extensions-logging/blob/0ba484a001067400e39732191affe429ff886fcb/src/Gelf.Extensions.Logging/GelfMessageProcessor.cs) processes a message, it calls [`GelfUdpClient.SendMessageAsync`](https://github.com/mattwcole/gelf-extensions-logging/blob/0ba484a001067400e39732191affe429ff886fcb/src/Gelf.Extensions.Logging/UdpGelfClient.cs#L42), which in turn calls `UDPClient.SendAsync`, which in turn [does a DNS lookup on every call](https://github.com/microsoft/referencesource/blob/a48449cb48a9a693903668a71449ac719b76867c/System/net/System/Net/Sockets/UDPClient.cs#L653). 

The impact of this becomes especially apparent when running in an environment without OS-level DNS caching, which is common when running in a container on Linux. In Kubernetes, for example, this implies a round-trip to a `coredns` pod (potentially not even running on the same node) for every log message, and as `GelfMessageProcessor` is single-threaded, this can cause logging to start lagging behind quite a bit under load. As the [capacity of the message buffer is limited](https://github.com/mattwcole/gelf-extensions-logging/blob/0ba484a001067400e39732191affe429ff886fcb/src/Gelf.Extensions.Logging/GelfMessageProcessor.cs#L20), this will at some point even start blocking application code.

Substituting the server's hostname with an IP address resolved these issues for us. I can wrap together an MR to solve this issue in the package itself, but I'm a bit torn on how much caching makes sense here.

**Comment by mattwcole** [comment]
Hi, thanks for reporting. I agree, it is wasteful to perform a DNS lookup for every request. Caching the lookup as you suggest sounds like a reasonable option. We could also just do the lookup once for simplicity - this would mirror how [`HttpGelfClient`](https://github.com/mattwcole/gelf-extensions-logging/blob/0ba484a001067400e39732191affe429ff886fcb/src/Gelf.Extensions.Logging/HttpGelfClient.cs) works since `HttpClient` doesn't respect DNS changes. I'd be interested to see how other popular logging libraries handle this.

As for the message buffer hitting capacity, this shouldn't block application code, however [messages will be lost](https://github.com/mattwcole/gelf-extensions-logging/blob/0ba484a001067400e39732191affe429ff886fcb/src/Gelf.Extensions.Logging/GelfMessageProcessor.cs#L59) - the lesser of two evils in my opinion.

**Comment by svenvanheugten** [comment]
> Hi, thanks for reporting. I agree, it is wasteful to perform a DNS lookup for every request. Caching the lookup as you suggest sounds like a reasonable option. We could also just do the lookup once for simplicity - this would mirror how [`HttpGelfClient`](https://github.com/mattwcole/gelf-extensions-logging/blob/0ba484a001067400e39732191affe429ff886fcb/src/Gelf.Extensions.Logging/HttpGelfClient.cs) works since `HttpClient` doesn't respect DNS changes. I'd be interested to see how other popular logging libraries handle this.

I looked at a few other logging libraries:

- NLog [creates a bound UDP socket and keeps it around](https://github.com/NLog/NLog/blob/733ce6e65045fd93de8bad6f9c5c67639e2d0978/src/NLog/Internal/NetworkSenders/UdpNetworkSender.cs#L93).
- Python's built in logging library [creates a bound UDP socket and keeps it around](https://github.com/python/cpython/blob/3.8/Lib/logging/handlers.py#L665).
- Log4net [only accepts an IP address in `UdpAppender`](https://github.com/apache/logging-log4net/blob/ce1b9fbb7a2a9ab60e80f3060d1397e57f10e1c4/src/log4net/Appender/UdpAppender.cs), and then [sends it over an unbound UDP socket](https://github.com/apache/logging-log4net/blob/ce1b9fbb7a2a9ab60e80f3060d1397e57f10e1c4/src/log4net/Appender/UdpAppender.cs#L409).

I was a bit worried how keeping around a bound UDP socket would affect fail-overs and load-balancing over different pods. I [tested those things](https://github.com/svenvanheugten/k8s-udp-test) to be sure, and:
- Fail-overs work fine. When a pod is deleted the subsequent traffic is quickly routed to another pod.
- Load-balancing doesn't seem to work. All traffic is always routed to the same pod. However, this doesn't just happen when using a bound UDP socket, but with _any_ re-use of `UdpClient` instances. I suspect this has to do with https://github.com/kubernetes/kubernetes/issues/76517 and the fact that [`UdpClient` re-uses the same socket even when it is unbound](https://github.com/microsoft/referencesource/blob/master/System/net/System/Net/Sockets/UDPClient.cs#L1044). The only way to avoid this seems to be to create a new `UdpClient` for every message, but that's a different issue (if it is an issue at all).

But it also suffices to just explicitly resolve the DNS entry in advance and pass it to `SendAsync` on the unbound `UDPClient`. Both solutions are probably reasonable.

> As for the message buffer hitting capacity, this shouldn't block application code, however [messages will be lost](https://github.com/mattwcole/gelf-extensions-logging/blob/0ba484a001067400e39732191affe429ff886fcb/src/Gelf.Extensions.Logging/GelfMessageProcessor.cs#L59) - the lesser of two evils in my opinion.

Whoops, sorry, didn't notice that bit of code. I agree.

**Comment by mattwcole** [comment]
Wow, great analysis, much appreciated! PR looks good, I'll get that merged and released as v2.0.1.
