### ISSUE TITLE
Use IExternalScopeProvider for logging scopes

### ISSUE THREAD

**Issue by epawlik** [mattwcole/gelf-extensions-logging#54]
The default logger factory can provide a scope implementation via the `ISupportExternalScope` and `IExternalScopeProvider` interfaces.

For reference, see:
[Microsoft.Extensions.Logging/LoggerFactory.cs](https://github.com/dotnet/runtime/blob/1cdafd27e4afd2c916af5df949c13f8b373c4335/src/libraries/Microsoft.Extensions.Logging/src/LoggerFactory.cs#L191) and [Microsoft.Extensions.Logging/LoggerFactoryScopeProvider.cs](https://github.com/dotnet/runtime/blob/1d9e50cb4735df46d3de0cee5791e97295eaf588/src/libraries/Microsoft.Extensions.Logging/src/LoggerFactoryScopeProvider.cs)

This gets you features like [dotnet/runtime#34305](https://github.com/dotnet/runtime/issues/34305)  when using the default logger factory instance.

Can support be added for `ISupportExternalScope` and `IExternalScopeProvider`?

**Comment by mattwcole** [comment]
Hi, apologies for the delay getting back to you. This looks useful, thanks. If you would like support added sooner rather than later feel free to put up a pull request, otherwise I'll take a look when I have some time.

**Comment by MichalSznajder** [comment]
Just for reference: this relates to getting SpanId, TraceId, ParentId fields in your logs.

**Comment by MichalSznajder** [comment]
FYI Probably it should be possible to fake it with approach from https://github.com/serilog/serilog-aspnetcore/issues/207#issuecomment-702665756 and adding mentioned field in when AdditionalFieldsFactory() is called.

**Comment by mattwcole** [comment]
I finally got around to adding support for this, use [v2.3.0-pre2](https://www.nuget.org/packages/Gelf.Extensions.Logging/2.3.0-pre2) to give it a try.
