### ISSUE TITLE
.Net framework support

### ISSUE THREAD

**Issue by fabercs** [mattwcole/gelf-extensions-logging#57]
I would like to use this library for my ASP.Net 4.5 project, is there any source/guide how to implement this for my project?

**Comment by mattwcole** [comment]
Hi, this library is for use with Microsoft.Extensions.Logging and the oldest version targets `netstandard1.3` which supports .NET Framework 4.6 and above. If that isn't a blocker for you then you could use `Gelf.Extensions.Logging` [v1.5.2](https://www.nuget.org/packages/Gelf.Extensions.Logging/1.5.2) and use `LoggerFactory` like the example [here](https://stackoverflow.com/a/46817838/4832982). Alternatively you could look at shipping logs via [log4net](https://github.com/jjchiw/gelf4net), [NLog](https://github.com/mantasaudickas/NLog.Gelf) or [Serilog](https://github.com/whir1/serilog-sinks-graylog).
