### ISSUE TITLE
Gelf.Extensions.Logging does not support options reload

### ISSUE THREAD

**Issue by MichalSznajder** [mattwcole/gelf-extensions-logging#61]
It would be nice to allow reload of config while app is running. It allows quick adjustments on production while debugging.

Probably ConsoleLogger approach could be an inspiration:

- https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/Microsoft.Extensions.Logging.Console/src/ConsoleLoggerProvider.cs
- https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/Microsoft.Extensions.Logging.Console/src/ConsoleLoggerExtensions.cs#L28

**Comment by mattwcole** [comment]
Agreed, this would be a great feature to add. Let me know if you plan to submit a PR, otherwise I will take a look at this and #54 within the next couple of weeks.

**Comment by MichalSznajder** [comment]
I'll write here in case I'll start working on it.

**Comment by mattwcole** [comment]
I have released a pre-release package with support for this. Give [v2.4.0-pre1](https://www.nuget.org/packages/Gelf.Extensions.Logging/2.4.0-pre1) a try.
