### ISSUE TITLE
Null Exception in GetMessageBytes because field.Value can be null

### ISSUE THREAD

**Issue by tomap** [mattwcole/gelf-extensions-logging#7]
Hi,

I stumbled upon a bug where field.Value.ToString() was producing a null exception because field.Value was null
see here:
https://github.com/mattwcole/gelf-extensions-logging/blob/dev/src/Gelf.Extensions.Logging/UdpGelfClient.cs#L54 
To reproduce, I'm using latest version of Swagger UI:
Swashbuckle.AspNetCore in ASP.Net Core 2.1 (but I believe this can also be reproduced in ASP.Net Core 2.0

Could you transform this line with 
```
messageJson[$"_{field.Key}"] = field.Value as string ?? field.Value?.ToString(); 
```
that did fix the issue for me

This might be a bit difficult for you to reproduce, please, do tell me if you need a sample

Thank you

Thomas

**Comment by mattwcole** [comment]
Hi Thomas, thanks for reporting this, it looks like a bug to me! I'll try to get a fix released in the next few days unless you feel like putting up a PR.

**Comment by mattwcole** [comment]
I finally found some time to fix this. You can grab v1.2.2-pre1 from NuGet once it has indexed. I'll release a stable version shortly. Thanks again for reporting.
