### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by mschatt** [mattwcole/gelf-extensions-logging#76]
Hello 
While scanning our solution, we found a security issue with the current Gelf.Extensions.Logging Package which still has a dependency on System.Text.Regularexpressions.4.3.0 which has a security issue: ![image](https://github.com/mattwcole/gelf-extensions-logging/assets/106265156/aea3811a-6419-4e29-9f52-f3d9bc14b369) Please fix the dependency as soon as possible, thanks ![image](https://github.com/mattwcole/gelf-extensions-logging/assets/106265156/d54d96e1-f164-4dba-b499-7c30ee98c9d1)

**Comment by mschatt** [comment]
Will this issue be resolved?

**Comment by mattwcole** [comment]
A quick search of [your vulnerability code](https://docs.mend.io/en-US/bundle/wsk/page/is_my_project_vulnerable_to_cve-2019-0820_.html) shows that this is an issue with the runtime, and not this library. You can safely ignore it since you are using .NET 6.
