### ISSUE TITLE
Need help with log errors in Main

### ISSUE THREAD

**Issue by ornic** [mattwcole/gelf-extensions-logging#77]
Is it possible to get logger to send errors inside `public static void Main(string[] args)`?

**Comment by mattwcole** [comment]
This question applies to `Microsoft.Extensions.Logging` in general and not just this provider. Assuming you are using an application builder in your entrypoint, you can get a logger instance after you have built the app as shown [here](https://stackoverflow.com/a/46298052).

**Comment by ornic** [comment]
Thank you!

I moving from NLog (it can't read variables from multi-layered IConfigurations) and there is a LogManager class there that can be bootstrapped before CreateBuilder to log any error during app setup process. And I was hoping that subj has some similar ability.

But I can live without it :)
