### ISSUE TITLE
Support the @ structure capturing operator

### ISSUE THREAD

**Issue by darraghjones** [mattwcole/gelf-extensions-logging#78]
According to https://messagetemplates.org/

> Prefixing a property name with the @ structure capturing operator is a hint that the the structure of the corresponding argument should be preserved, for example, by serialization

What do you think about adding support for this?

**Comment by mattwcole** [comment]
I don't think that sounds unreasonable, especially if it is something other providers support. I've not used Graylog for years so I don't know how it would handle this though. The examples in the [GELF spec](https://go2docs.graylog.org/5-1/getting_in_log_data/gelf.html#GELFPayloadSpecification) only show sending key value pairs.

**Comment by mattwcole** [comment]
Closing for now, let me know if you have some ideas on how this would work. Can re-open if there is still interest.
