### ISSUE TITLE
UDP sets DontFragment bit by default, dropping large GELF chunks

### ISSUE THREAD

**Issue by StephenCleary** [mattwcole/gelf-extensions-logging#79]
The [default value of `UdpClient.DontFragment` is `true`](https://learn.microsoft.com/en-us/dotnet/api/system.net.sockets.udpclient.dontfragment). This means that any UDP GELF chunk greater than the MTU will be silently dropped. The observed behavior is that all small log messages work fine but any large log messages just don't show up.

IMO, the best solution is to set `DontFragment` to `false` [here](https://github.com/mattwcole/gelf-extensions-logging/blob/99ac2e9b5d20030d4719ba75b110113b758ac11f/src/Gelf.Extensions.Logging/UdpGelfClient.cs#L28). This does mean that large log messages will be chunked and then fragmented, but that's better than dropping them completely.

A more complex solution is possible: detecting MTU (and MTU changes) by keeping `DontFragment` set and handling the ICMP Fragmentation Needed responses, somewhat similar to how QUIC detects MTU. But that's probably very complex and way out of scope for this library.

**Comment by mattwcole** [comment]
By chance, there happens to be [a test case](https://github.com/mattwcole/gelf-extensions-logging/blob/99ac2e9b5d20030d4719ba75b110113b758ac11f/test/Gelf.Extensions.Logging.Tests/UdpGelfLoggerTests.cs#L28) that covers this scenario, sending an uncompressed message of 10000 bytes (chunk size 8192) to Graylog and using the Graylog API to verify that the message has arrived in its entirety.

When the tests run in Docker (as they do in CI), the MTU is less than 8192, so this test should fail. Interestingly it does fail if `UdpClient.DontFragment` is set to `true` explicitly. Could the default behaviour be incorrectly documented?

I've replicated the above on branch [debug-udp-mtu](https://github.com/mattwcole/gelf-extensions-logging/tree/debug-udp-mtu). Set `DontFragment` and run the following to see the impact.

```sh
docker compose build tests
docker compose run tests
```

**Comment by StephenCleary** [comment]
Sorry for the misdirection. I agree that the `DontFragment` docs are incorrect; on .NET Core (Linux and Windows) and .NET Framework, `DontFragment` does default to `false`, and on Windows at least, the DF bit is not set.

I am having a problem sending large messages to Graylog; I'll look into it in more detail. It seems as though the large messages are not actually sent (Wireshark doesn't see them). I'm running on .NET Framework on Windows.

**Comment by StephenCleary** [comment]
OK, I think I found it. The problem is that my Graylog server is running on an Azure VM, and "IP fragmentation is not supported in Azure" ([source](https://learn.microsoft.com/en-us/azure/virtual-network/virtual-network-tcpip-performance-tuning#fragmentation)).

So my only real solution is to set `MaxChunkSize` to a value below the MTU.

Thank you, and sorry for the trouble!
